### PR TITLE
Removed the Avalonia.ReactiveUI dependency

### PR DESCRIPTION
**Pull request by CrackAndDie**
Vanilla [Prism](https://github.com/PrismLibrary/Prism) doesn't have dependencies on libraries like the [ReactiveUI](https://github.com/reactiveui/ReactiveUI) (libraries that help us to create UI with code weaving). So I think that Prism.Avalonia also should not use it. 
The only thing used in ReactiveUI was subscribing on *IObservable* interface implementations with lambda methods. In my opinion this is innormal to depend on the library and use only a thing.
So now there is a *AnonymousObserver* implementation taken from ReactiveUI and *ObservableExtensions* that gives us the *Subscribe* method for *IObservable*s.
Tests added :)

### CODE REVIEW

**Comment by DamianSuess** [comment]
For this PR, may you please update the description of this PR to explain, "_added some required implementations_".

This assists future readers of this PR to understand what was changed and how it affects the library.

**Comment by CrackAndDie** [comment]
Just updated the description of the RP

**Comment by Mrxx99** [comment]
You can also look at https://github.com/devlooped/RxFree which are source only reactive extensions with the basic feature of System.Reactive, so you don't have to reimplement the helpers. The extensions also will be internal to your project so consumers won't see them.

**Comment by CrackAndDie** [comment]
@Mrxx99 I've implemented only the [Subscribe](https://github.com/AvaloniaCommunity/Prism.Avalonia/pull/118/commits/fe74aacc0cfc7c014948c42d286674ef9af73b79#diff-df3577f9d79d1ba6f307216658be60f1ca5dfb9b2c5be5a9dff5d6d68e78ab4b) extension method for *IObservable*. *AnonymousObserver* (*IObserver* implementation) was removed in the third commit of mine because it is already in *Avalonia.Base*. I don't see any dependencies on *System.Reactive* 🤔

**Comment by DamianSuess** [comment]
This will be merged in shortly. Sorry for the delay, had to tend to other repos over the past couple weeks

**Comment by DamianSuess** [comment]
All set

**Pull request merged**
