### PR TITLE
Merge AvaloniaUI v0.10.4 into Master

### PR DESCRIPTION
**Pull request by DamianSuess**
This is a simple pull request which targets the latest AvaloniaUI v0.10.4 and upgrades the examples to use .NET 5.
Also, as a goodie, I've included the `.editorconfig` from PrismLibrary to stay compatible with their coding format.

### CODE REVIEW

**Comment by DamianSuess** [comment]
Tested locally with .NET 5 with success. Let me know if there is anything else required prior to the PR being accepted.

Just as an FYI, I'm looking into upgrading to Prism 8.1.92.  Please let me know if this effort is already underway elsewhere.

**Comment by OmidID** [comment]
@DamianSuess Hello and thanks for the PR. 
Unfortunately, the changes are faulty. All the dependencies and csproj files are organized in props files and this is not a correct way to update dependencies.
I have an article that I hope it is helpful, and you could create another PR following these rules.
https://omidid.com/topic/Howtoorganizeyourcsprojandlibrariesusingpropsfiles

**Comment by DamianSuess** [comment]
Thank you, I'll take care of it right away

**Comment by DamianSuess** [comment]
Ready for review 👍

**Comment by DamianSuess** [comment]
awesome, thank you @OmidID

**Pull request merged**
